# Wrangler configuration for Cloudflare Pages with Next.js
# Learn more at https://developers.cloudflare.com/pages/framework-guides/deploy-a-nextjs-site/

name = "sage-wireframe-navigator"
account_id = "c5d22100f6fcee337306f3dcf4037485"
compatibility_date = "2024-10-15"
compatibility_flags = ["nodejs_compat"]

# Pages configuration for Next.js
pages_build_output_dir = ".next"

# Environment variables (add your own as needed)
[vars]
NODE_ENV = "production"
NEXT_PUBLIC_SITE_URL = "https://sage-wireframe-navigator.pages.dev"

# Custom domains (configure after deployment)
# [[routes]]
# pattern = "wireframes.sagehealthcare.sa"
# custom_domain = true

# Build configuration
[build]
command = "npm run build:cf"

# KV namespaces (if needed for data storage)
# [[kv_namespaces]]
# binding = "SAGE_KV"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Headers for security and performance
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache static assets
[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.png"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.jpg"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.svg"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Redirects (if needed)
# [[redirects]]
# from = "/old-path"
# to = "/new-path"
# status = 301
