// Auto-generated by scripts/cache-fallback.mjs — do not edit manually.
// Run: NEXT_PUBLIC_API_BASE_URL=<url> node scripts/cache-fallback.mjs
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const fallbacks: Record<string, Record<string, any>> = {}

export default fallbacks
